export const ADD_WORKER = 'Adds a new worker to the Database';
export const DELETE_WORKER = 'Deletes a user fromt he DB';
export const UPDATE_INVENTORY = 'Changes the inventory levels in the system';
export const LOAD_WORKERS = 'loads the workers from the DB to the redux state for passing down to the compoenents'
export const POST_ORDER = 'Creates a new order';
export const LOAD_ORDERS = 'Loads orders from mock api to state';
export const GET_ORDERS = 'Gets orders from mock api';
export const LOAD_TRANSACTIONS = 'Gets list of transactions'
export const POST_TRANSACTION = 'Creates a new transaction';
export const PUT_ORDER = 'Updates an order';
export const GET_INVENTORY = 'Gets the inventory';
